-- Create table for domain-specific terms (data-driven)
CREATE TABLE IF NOT EXISTS IntentDomainTerms (
  TermID INT AUTO_INCREMENT PRIMARY KEY,
  Term VARCHAR(255) NOT NULL,
  Domain VARCHAR(50) NOT NULL,
  IsActive TINYINT(1) NOT NULL DEFAULT 1,
  CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_term_domain (Term, Domain)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
